---
- name: Install Prometheus on Ubuntu and CentOS
  hosts: ubuntu, centos
  become: yes
  become_method: sudo
  become_user: root
  become_flags: "-H -S"  # This is for providing the sudo password securely
  roles:
    - prometheus

- name: Configure DNS on CentOS
  hosts: centos
  roles:
    - dns_config

- name: Copy and Install Prometheus on CentOS
  hosts: centos
  become: yes
  become_method: sudo
  become_user: root
  become_flags: "-H -S"
  tasks:
    - name: Copy Prometheus binary to CentOS
      copy:
        src: files/prometheus-2.8.1.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.8.1.linux-amd64.tar.gz

    - name: Extract Prometheus binary on CentOS
      command: tar -xzf /tmp/prometheus-2.8.1.linux-amd64.tar.gz -C /usr/local/bin
